<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/all.min.css">
  <link rel="stylesheet" href="css/aos.css">
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="shortcut icon" href="imagens/foguete.png">
  <link rel="stylesheet" type="text/css" href="css/style.css">

  <title>TEXT ADVENTURE</title>
</head>

<body>
  <div id="imagem-telainteira">
    <!--INICIO DO CABEÇALHO-->
    <header>
      <nav class="navbar navbar-expand-lg navbar-pizza">
        <div class="container-fluid">
          <a class="navbar-brand" active aria-current="page" href="#">INICIO</a>
          <button class="navbar-toggler"  type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link"  href="#">HISTÓRIA</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">SOBRE</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  DADOS DO JOGO
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">LOAD</a></li>
                  <li><a class="dropdown-item" href="#">SAVE</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="#">RESTART</a></li>
                </ul>
              </li>

            </ul>
            
          </div>
        </div>
      </nav>
    </header>
    <!--FIM DO CABEÇALHO-->

    <!--INICIO DA AREA PRINCIPAL-->
    <div class="container-fluid">
      <h1 class="text-center titulo-jogo "> JORNADA DE JASPER </h1>
      <br>
      <div class="mb-5" >
      <p><?= $arrayAssociativo->mensagem ?></p>
        <label for="comandoInput" class="form-label "> Digite HELP para exibir os comandos....</label>
        <textarea class="caixa-texto form-control" id="resposta" name="resposta" rows="15" readonly>
        
        </textarea>
        
      </div>


      <div class="text-center">
     <form action="index.php" method="get">
      <div class="form-group">
           
                <input type="text" name="comando"/>
                <input type="text" name="save" value="<?= $arrayAssociativo->idSave ?>" readonly/>
                <input type="submit"/>
                <button type="button" class="btn btn-secondary btn-lg" id="enviarComandoBtn">ENVIAR</button>
      </div>
            </form>
        </div>
        
      
      </div>
      



    </div>
  </div>
  <!--FIM DA AREA PRINCIPAL-->

  <!-- INICIO SCRIPT BOOTSTRAP E JS -->




  <script src="js/bootstrap.bundle.min.js">

  </script>
  <script src="js/aos.css">

  </script>
  <script src="https://kit.fontawesome.com/956ac241f2.js" crossorigin="anonymous"></script>
  <!-- FIM SCRIPT BOOTSTRAP E JS -->


  
</body>

</html>